SELECT      NAME||'('||SUBSTR(OCCUPATION,1,1)||')' AS COL1
FROM        OCCUPATIONS A
UNION
SELECT      'There are a total of '||COUNT(1)||' '||LOWER(OCCUPATION)||'s.' AS COL1
FROM        OCCUPATIONS B
GROUP BY    OCCUPATION
ORDER BY    COL1 ASC;