SELECT N,
CASE
    WHEN P IS NULL THEN 'Root'  
    WHEN P IS NOT NULL AND ISPARENT = 'Y' THEN 'Inner'
    WHEN P IS NOT NULL AND ISPARENT = 'N' THEN 'Leaf'
END
FROM
(SELECT A.N AS N , A.P AS P, NVL((SELECT 'Y' FROM BST C WHERE C.P=A.N AND ROWNUM=1),'N') AS ISPARENT
FROM BST A
)
ORDER BY N;