SELECT A.COMPANY_CODE,B.FOUNDER,
COUNT(DISTINCT LEAD_MANAGER_CODE),
COUNT(DISTINCT SENIOR_MANAGER_CODE),
COUNT(DISTINCT MANAGER_CODE),
COUNT(DISTINCT EMPLOYEE_CODE)
FROM
(SELECT  DISTINCT COMPANY_CODE,
        LEAD_MANAGER_CODE,
        SENIOR_MANAGER_CODE,
        MANAGER_CODE,
        EMPLOYEE_CODE
FROM    EMPLOYEE) A, COMPANY B
WHERE A.COMPANY_CODE = B.COMPANY_CODE
GROUP BY A.COMPANY_CODE, B.FOUNDER
ORDER BY A.COMPANY_CODE;