SELECT HACKER_ID, HACKER_NAME FROM (
SELECT HACKER_ID,HACKER_NAME,SCORE_STATUS,COUNT(SCORE_STATUS)
FROM
(SELECT S.SUBMISSION_ID SUBMISSION_ID,
        S.HACKER_ID HACKER_ID,
        H.NAME HACKER_NAME,
        S.CHALLENGE_ID CHALLENGE_ID,
        C.DIFFICULTY_LEVEL DIFFICULTY_LEVEL,
        S.SCORE SCORE,
        D.SCORE MAXSCORE,
        CASE WHEN S.SCORE = D.SCORE THEN 'FULL_SCORE' ELSE 'NOT_FULL' END AS SCORE_STATUS
FROM    SUBMISSIONS S,
        CHALLENGES C,
        HACKERS H,
        DIFFICULTY D
WHERE   S.CHALLENGE_ID  =   C.CHALLENGE_ID
AND     C.DIFFICULTY_LEVEL    =   D.DIFFICULTY_LEVEL
AND     S.HACKER_ID = H.HACKER_ID)
GROUP BY HACKER_ID, HACKER_NAME, SCORE_STATUS
HAVING COUNT(SCORE_STATUS)>1 AND SCORE_STATUS='FULL_SCORE'
ORDER BY COUNT(SCORE_STATUS) DESC, HACKER_ID ASC);