select * from (
SELECT CITY, LENGTH(CITY) 
FROM STATION
GROUP BY CITY, LENGTH(CITY)
HAVING LENGTH(CITY) = (SELECT MIN(LENGTH(CITY)) FROM STATION)
ORDER BY CITY)
where rownum=1
union
select * from (
SELECT CITY, LENGTH(CITY) 
FROM STATION
GROUP BY CITY, LENGTH(CITY)
HAVING LENGTH(CITY) = (SELECT MAX(LENGTH(CITY)) FROM STATION)
ORDER BY CITY)
where rownum=1
;